"use client";

type WebsitePreviewProps = {
  data: any;
};

export default function WebsitePreview({ data }: WebsitePreviewProps) {
  if (!data) return null;

  const theme = data.theme || data.colors || {
    background: "#0f0a05",
    surface: "#1b1208",
    primary: "#fff7ed",
    secondary: "#facc15",
    accent: "#f97316",
    muted: "#d6b98c",
  };

  const hero = data.hero || {
    eyebrow: "AI Generated Website",
    headline: data.title || "Premium Website Preview",
    subheadline: data.tagline || "Generated by OmegaCrownAI.",
    primaryCta: "Get Started",
    secondaryCta: "Learn More",
  };

  const products = data.products || [];
  const features = data.features || [];
  const testimonials = data.testimonials || [];
  const navigation = data.navigation || data.pages || ["Home", "About", "Contact"];
  const assets = data.assets || {};

  return (
    <div
      className="overflow-hidden rounded-2xl border border-[#2a2a33] shadow-2xl"
      style={{
        background: `linear-gradient(135deg, ${theme.background || "#0f0a05"}, #050505)`,
        color: theme.primary || "#fff7ed",
      }}
    >
      <div className="border-b border-white/10 px-6 py-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-3">
            {assets.logo && (
              <img
                src={assets.logo}
                alt="Logo"
                className="h-12 w-12 rounded-xl bg-white/10 object-contain p-2"
              />
            )}

            <div>
              <div className="text-lg font-bold">
                {data.business || data.title || "Generated Website"}
              </div>
              <div className="text-xs opacity-70">
                {data.style || "Premium AI-generated website"}
              </div>
            </div>
          </div>

          <div className="flex flex-wrap gap-3 text-xs opacity-80">
            {navigation.slice(0, 5).map((item: string) => (
              <span key={item}>{item}</span>
            ))}
          </div>
        </div>
      </div>

      <section className="grid gap-8 px-6 py-10 md:grid-cols-[1.1fr_0.9fr] md:px-10 md:py-14">
        <div>
          <div
            className="mb-4 inline-flex rounded-full px-3 py-1 text-xs font-medium"
            style={{
              background: `${theme.accent || "#f97316"}22`,
              color: theme.secondary || "#facc15",
            }}
          >
            {hero.eyebrow || "Premium Website"}
          </div>

          <h1 className="max-w-3xl text-4xl font-bold leading-tight md:text-6xl">
            {hero.headline || data.title || "Beautiful Website Generated by AI"}
          </h1>

          <p className="mt-5 max-w-2xl text-base leading-7 opacity-75">
            {hero.subheadline ||
              data.tagline ||
              "A polished homepage concept with premium layout, cards, sections, and call-to-action areas."}
          </p>

          <div className="mt-7 flex flex-wrap gap-3">
            <button
              className="rounded-xl px-5 py-3 text-sm font-semibold text-black"
              style={{ background: theme.secondary || "#facc15" }}
            >
              {hero.primaryCta || "Get Started"}
            </button>

            <button className="rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold">
              {hero.secondaryCta || "Learn More"}
            </button>
          </div>

          <div className="mt-7 flex flex-wrap gap-2">
            {(data.trustBadges || ["AI Generated", "Premium Design", "Project Saved"]).map(
              (badge: string) => (
                <span
                  key={badge}
                  className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs opacity-80"
                >
                  {badge}
                </span>
              )
            )}
          </div>
        </div>

        <div
          className="rounded-3xl border border-white/10 p-5 shadow-2xl"
          style={{ background: theme.surface || "#1b1208" }}
        >
          <div className="rounded-2xl bg-white/10 p-4">
            {assets.hero ? (
              <img
                src={assets.hero}
                alt="Hero"
                className="h-48 w-full rounded-xl object-cover"
              />
            ) : (
              <div className="h-48 rounded-xl bg-gradient-to-br from-white/20 to-white/5" />
            )}
          </div>

          <div className="mt-5 grid gap-3">
            {(products.length > 0
              ? products.slice(0, 3)
              : [
                  {
                    name: "Signature Offer",
                    description: "A featured product or service generated from your prompt.",
                    price: "$29",
                    badge: "Popular",
                  },
                  {
                    name: "Premium Package",
                    description: "A high-value offer designed for conversion.",
                    price: "$59",
                    badge: "Best Seller",
                  },
                ]
            ).map((product: any, index: number) => (
              <div
                key={index}
                className="rounded-2xl border border-white/10 bg-black/20 p-4"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="font-semibold">{product.name}</div>
                    <div className="mt-1 text-xs opacity-70">
                      {product.description}
                    </div>
                  </div>
                  <div
                    className="rounded-full px-2 py-1 text-xs font-semibold text-black"
                    style={{ background: theme.secondary || "#facc15" }}
                  >
                    {product.price || product.badge || "New"}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="grid gap-4 px-6 pb-10 md:grid-cols-3 md:px-10">
        {(features.length > 0
          ? features.slice(0, 3)
          : [
              {
                title: "Premium Layout",
                description: "Hero, cards, trust badges, and strong CTA sections.",
              },
              {
                title: "Conversion Focused",
                description: "Designed to turn visitors into customers.",
              },
              {
                title: "Mobile Ready",
                description: "Responsive structure for phone and desktop.",
              },
            ]
        ).map((feature: any, index: number) => (
          <div
            key={index}
            className="rounded-2xl border border-white/10 bg-white/5 p-5"
          >
            <div className="text-lg font-semibold">{feature.title}</div>
            <div className="mt-2 text-sm leading-6 opacity-70">
              {feature.description}
            </div>
          </div>
        ))}
      </section>

      {testimonials.length > 0 && (
        <section className="grid gap-4 px-6 pb-10 md:grid-cols-2 md:px-10">
          {testimonials.slice(0, 2).map((item: any, index: number) => (
            <div
              key={index}
              className="rounded-2xl border border-white/10 bg-black/20 p-5"
            >
              <div className="text-sm leading-6 opacity-80">“{item.quote}”</div>
              <div className="mt-3 text-sm font-semibold">{item.name}</div>
            </div>
          ))}
        </section>
      )}

      <section className="border-t border-white/10 px-6 py-8 md:px-10">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <div className="text-2xl font-bold">
              {data.footer?.headline || "Ready to get started?"}
            </div>
            <div className="mt-1 text-sm opacity-70">
              {data.tagline || "Built with OmegaCrownAI Website Builder."}
            </div>
          </div>

          <button
            className="rounded-xl px-5 py-3 text-sm font-semibold text-black"
            style={{ background: theme.secondary || "#facc15" }}
          >
            {data.footer?.cta || "Contact Us"}
          </button>
        </div>
      </section>
    </div>
  );
}
