import fs from "fs";
import path from "path";
import { NextResponse } from "next/server";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const { projectId } = await params;
    const body = await req.json();

    const instruction = String(body?.instruction || "Regenerate sovereign artifact.");
    const artifactDir = path.join(process.cwd(), "data", "generated-artifacts", projectId);
    const runPath = path.join(process.cwd(), "data", "sovereign-runs", `${projectId}.json`);

    if (!fs.existsSync(runPath)) {
      return NextResponse.json({ ok: false, error: "Run not found." }, { status: 404 });
    }

    fs.mkdirSync(artifactDir, { recursive: true });

    const versionsDir = path.join(artifactDir, "versions");
    fs.mkdirSync(versionsDir, { recursive: true });

    const existingVersions = fs
      .readdirSync(versionsDir)
      .filter((name) => /^v\d+$/.test(name));

    const nextVersion = `v${existingVersions.length + 1}`;
    const versionDir = path.join(versionsDir, nextVersion);
    fs.mkdirSync(versionDir, { recursive: true });

    const run = JSON.parse(fs.readFileSync(runPath, "utf8"));

    const regeneratedHtml = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${projectId} ${nextVersion}</title>
  <style>
    body { margin:0; font-family:Arial,sans-serif; background:#020617; color:white; }
    main { max-width:1100px; margin:0 auto; padding:64px 24px; }
    .card { border:1px solid rgba(34,211,238,.35); background:rgba(15,23,42,.92); border-radius:28px; padding:36px; }
    .eyebrow { color:#67e8f9; letter-spacing:.25em; text-transform:uppercase; font-size:12px; font-weight:900; }
    h1 { font-size:52px; line-height:1; margin:20px 0; }
    p { color:#cbd5e1; line-height:1.8; font-size:18px; }
  </style>
</head>
<body>
  <main>
    <section class="card">
      <div class="eyebrow">OmegaCrownAI Regenerated Artifact ${nextVersion}</div>
      <h1>${run.intent?.toUpperCase() || "SOVEREIGN"} Build Upgrade</h1>
      <p>${instruction}</p>
      <p>${run.prompt || ""}</p>
    </section>
  </main>
</body>
</html>`;

    const notes = `# Artifact ${nextVersion}

Project: ${projectId}
Runtime: ${run.runtimeId}
Intent: ${run.intent}

## Regeneration Instruction
${instruction}

## Status
Generated by OmegaCrownAI sovereign regeneration engine.
`;

    fs.writeFileSync(path.join(versionDir, "index.html"), regeneratedHtml);
    fs.writeFileSync(path.join(versionDir, "notes.md"), notes);
    fs.writeFileSync(path.join(artifactDir, "index.html"), regeneratedHtml);

    run.events = Array.isArray(run.events) ? run.events : [];
    run.artifacts = Array.isArray(run.artifacts) ? run.artifacts : [];

    run.events.push(`Artifact ${nextVersion} regenerated: ${instruction}`);
    run.artifacts.push({
      id: `${projectId}-${nextVersion}`,
      type: "html-version",
      title: `Generated Artifact ${nextVersion}`,
      status: "generated",
      path: `data/generated-artifacts/${projectId}/versions/${nextVersion}/index.html`,
    });

    run.status = "running";
    run.updatedAt = new Date().toISOString();

    fs.writeFileSync(runPath, JSON.stringify(run, null, 2));

    return NextResponse.json({
      ok: true,
      projectId,
      version: nextVersion,
      preview: `data/generated-artifacts/${projectId}/versions/${nextVersion}/index.html`,
      eventCount: run.events.length,
      artifactCount: run.artifacts.length,
    });
  } catch {
    return NextResponse.json({ ok: false, error: "Failed to regenerate artifact." }, { status: 500 });
  }
}
