export function getAuditDatabaseMigrationBlueprint() {
  return {
    system: "OmegaCrownAI Audit Database Migration Blueprint",
    phase: "v19.1 Phase 211",
    status: "audit_database_migration_blueprint_ready",
    purpose:
      "Define the real database migration plan for OmegaCrownAI sovereign audit persistence, including core audit events, connector audit events, execution action logs, memory writes, deployments, incidents, indexes, relationships, and no-secret storage rules.",
    corePrinciple:
      "Audit persistence must be append-only, relational, indexed, replayable, redacted, and safe. The database must store hashes/references and evidence labels, never raw secrets or sensitive payloads.",

    migrationOrder: [
      {
        step: 1,
        table: "audit_events",
        reason: "Core parent audit table used by connector, execution, memory, deployment, incident, and governance records.",
      },
      {
        step: 2,
        table: "connector_audit_events",
        reason: "Connector permission gate, install, action, disconnect, and healthcheck audit records.",
      },
      {
        step: 3,
        table: "execution_action_runs",
        reason: "Execution runner canonical action run table.",
      },
      {
        step: 4,
        table: "execution_action_payloads",
        reason: "Safe input/output hash and reference table for action runs.",
      },
      {
        step: 5,
        table: "execution_action_evidence",
        reason: "Evidence records for builds, route checks, connector events, artifacts, and validation.",
      },
      {
        step: 6,
        table: "execution_action_errors",
        reason: "Error class, root cause, repair recommendation, and prevention notes.",
      },
      {
        step: 7,
        table: "execution_action_rollbacks",
        reason: "Rollback/recovery availability and recovery notes.",
      },
      {
        step: 8,
        table: "memory_audit_events",
        reason: "Governed memory writes, corrections, confidence labels, and forget/delete records.",
      },
      {
        step: 9,
        table: "deployment_audit_events",
        reason: "Build, PM2, route smoke check, commit, and rollback evidence.",
      },
      {
        step: 10,
        table: "incident_events",
        reason: "Reliability incidents, severity, route, error class, root cause, and prevention rules.",
      },
    ],

    prismaModels: [
      {
        model: "AuditEvent",
        table: "audit_events",
        fields: [
          "id String @id @default(cuid())",
          "eventType String",
          "actor String",
          "role String",
          "source String",
          "riskLevel String",
          "decision String",
          "status String",
          "correlationId String",
          "evidenceJson Json",
          "metadataRef String?",
          "redacted Boolean @default(true)",
          "createdAt DateTime @default(now())",
        ],
        indexes: [
          "@@index([eventType, createdAt])",
          "@@index([correlationId])",
          "@@index([actor])",
          "@@index([source])",
          "@@index([riskLevel, status])",
        ],
      },
      {
        model: "ConnectorAuditEvent",
        table: "connector_audit_events",
        fields: [
          "id String @id @default(cuid())",
          "auditEventId String",
          "connectorId String",
          "actionId String?",
          "permission String?",
          "requestedGate String?",
          "approvalRequired Boolean @default(false)",
          "blocked Boolean @default(false)",
          "userApproved Boolean @default(false)",
          "inputHash String?",
          "outputHash String?",
          "rollbackNote String?",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["auditEventId -> audit_events.id"],
        indexes: [
          "@@index([connectorId, actionId])",
          "@@index([permission])",
          "@@index([blocked])",
        ],
      },
      {
        model: "ExecutionActionRun",
        table: "execution_action_runs",
        fields: [
          "id String @id @default(cuid())",
          "auditEventId String?",
          "actionId String",
          "actionName String",
          "executionCategory String",
          "actor String",
          "role String",
          "approvalGate String",
          "approvalStatus String",
          "sandboxMode Boolean @default(true)",
          "runMode String",
          "status String",
          "riskLevel String",
          "correlationId String",
          "createdAt DateTime @default(now())",
          "startedAt DateTime?",
          "completedAt DateTime?",
        ],
        relationships: ["auditEventId -> audit_events.id"],
        indexes: [
          "@@index([actionId, status])",
          "@@index([correlationId])",
          "@@index([executionCategory])",
          "@@index([riskLevel, status])",
        ],
      },
      {
        model: "ExecutionActionPayload",
        table: "execution_action_payloads",
        fields: [
          "id String @id @default(cuid())",
          "executionActionRunId String",
          "inputHash String?",
          "outputHash String?",
          "inputRef String?",
          "outputRef String?",
          "redactionStatus String",
          "containsSecret Boolean @default(false)",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["executionActionRunId -> execution_action_runs.id"],
        indexes: ["@@index([executionActionRunId])", "@@index([containsSecret])"],
      },
      {
        model: "ExecutionActionEvidence",
        table: "execution_action_evidence",
        fields: [
          "id String @id @default(cuid())",
          "executionActionRunId String",
          "evidenceType String",
          "evidenceLabel String",
          "evidenceRef String?",
          "status String",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["executionActionRunId -> execution_action_runs.id"],
        indexes: ["@@index([executionActionRunId])", "@@index([evidenceType, status])"],
      },
      {
        model: "ExecutionActionError",
        table: "execution_action_errors",
        fields: [
          "id String @id @default(cuid())",
          "executionActionRunId String",
          "errorClass String",
          "errorMessageSafe String",
          "rootCause String?",
          "repairRecommendation String?",
          "preventionRule String?",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["executionActionRunId -> execution_action_runs.id"],
        indexes: ["@@index([executionActionRunId])", "@@index([errorClass])"],
      },
      {
        model: "ExecutionActionRollback",
        table: "execution_action_rollbacks",
        fields: [
          "id String @id @default(cuid())",
          "executionActionRunId String",
          "rollbackAvailable Boolean @default(false)",
          "rollbackType String?",
          "rollbackRef String?",
          "recoveryNote String",
          "verifiedAt DateTime?",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["executionActionRunId -> execution_action_runs.id"],
        indexes: ["@@index([executionActionRunId])", "@@index([rollbackAvailable])"],
      },
      {
        model: "MemoryAuditEvent",
        table: "memory_audit_events",
        fields: [
          "id String @id @default(cuid())",
          "auditEventId String",
          "memoryId String",
          "partition String",
          "sourceConfidence String",
          "writeReason String",
          "previousValueHash String?",
          "newValueHash String?",
          "reviewRequired Boolean @default(false)",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["auditEventId -> audit_events.id"],
        indexes: [
          "@@index([memoryId, partition])",
          "@@index([sourceConfidence])",
          "@@index([reviewRequired])",
        ],
      },
      {
        model: "DeploymentAuditEvent",
        table: "deployment_audit_events",
        fields: [
          "id String @id @default(cuid())",
          "auditEventId String",
          "commitHash String?",
          "buildStatus String",
          "pm2Status String?",
          "routeChecksJson Json",
          "logCheckStatus String?",
          "rollbackCommit String?",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["auditEventId -> audit_events.id"],
        indexes: [
          "@@index([commitHash])",
          "@@index([buildStatus])",
          "@@index([pm2Status])",
        ],
      },
      {
        model: "IncidentEvent",
        table: "incident_events",
        fields: [
          "id String @id @default(cuid())",
          "auditEventId String",
          "severity String",
          "service String",
          "route String?",
          "errorClass String?",
          "startedAt DateTime",
          "resolvedAt DateTime?",
          "rootCause String?",
          "preventionRule String?",
          "createdAt DateTime @default(now())",
        ],
        relationships: ["auditEventId -> audit_events.id"],
        indexes: [
          "@@index([severity, service, startedAt])",
          "@@index([errorClass])",
          "@@index([resolvedAt])",
        ],
      },
    ],

    noSecretColumnPolicy: [
      "No column may store raw OAuth tokens.",
      "No column may store API keys.",
      "No column may store passwords.",
      "No column may store bearer authorization headers.",
      "No column may store private keys.",
      "No column may store webhook secrets.",
      "No column may store raw sensitive payloads.",
      "Use inputHash, outputHash, metadataRef, evidenceRef, credentialRef, or opaque references instead.",
      "containsSecret must remain false for persisted action payload records.",
      "Audit query/export APIs must return redacted records only.",
    ],

    relationshipRules: [
      "Specialized audit tables should reference audit_events.id.",
      "Execution payload/evidence/error/rollback tables should reference execution_action_runs.id.",
      "Deleting audit events should be restricted or soft-retained for enterprise traceability.",
      "Redaction must happen before database write.",
      "Correlation id must be present for replayable workflows.",
    ],

    rollbackPlan: [
      "Before migration, create database backup or managed snapshot.",
      "Apply migration in staging first.",
      "Run smoke test against schema blueprint.",
      "Verify app build succeeds before production restart.",
      "If migration fails, roll back to previous migration and restore snapshot if needed.",
      "Do not delete existing audit records during rollback.",
    ],

    implementationSteps: [
      "Inspect existing Prisma/schema setup.",
      "Add audit models to Prisma schema or SQL migration.",
      "Run prisma format or SQL lint if available.",
      "Run migration locally/staging.",
      "Generate Prisma client if Prisma is used.",
      "Run npm run build.",
      "Run audit schema smoke tests.",
      "Restart PM2 only after build success.",
      "Verify production route 200 responses.",
    ],

    nextImplementationPhases: [
      "Audit Event Write Persistence",
      "Audit Event Query Persistence",
      "Audit Review UI Page",
      "Correlation Replay UI Page",
      "Audit Export Download Route",
    ],
  };
}
