import { Buffer } from "buffer";
import { getCustomerDownloadPackageRoute } from "@/lib/sovereign/customer-download-package-route";
import { generateRealFullStackArtifact } from "@/lib/sovereign/real-full-stack-artifact-generator";

type ZipFile = {
  path: string;
  content: string;
};

const crcTable = (() => {
  const table: number[] = [];
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(input: Buffer) {
  let crc = 0xffffffff;
  for (const byte of input) {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function dosDateTime(date = new Date()) {
  const year = Math.max(date.getFullYear(), 1980);
  const dosTime =
    (date.getHours() << 11) |
    (date.getMinutes() << 5) |
    Math.floor(date.getSeconds() / 2);

  const dosDate =
    ((year - 1980) << 9) |
    ((date.getMonth() + 1) << 5) |
    date.getDate();

  return { dosTime, dosDate };
}

export function createZipBuffer(files: ZipFile[]) {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;
  const { dosTime, dosDate } = dosDateTime();

  for (const file of files) {
    const fileName = Buffer.from(file.path.replace(/^\/+/, ""), "utf8");
    const data = Buffer.from(file.content, "utf8");
    const checksum = crc32(data);

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(dosTime, 10);
    localHeader.writeUInt16LE(dosDate, 12);
    localHeader.writeUInt32LE(checksum, 14);
    localHeader.writeUInt32LE(data.length, 18);
    localHeader.writeUInt32LE(data.length, 22);
    localHeader.writeUInt16LE(fileName.length, 26);
    localHeader.writeUInt16LE(0, 28);

    localParts.push(localHeader, fileName, data);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt16LE(dosTime, 12);
    centralHeader.writeUInt16LE(dosDate, 14);
    centralHeader.writeUInt32LE(checksum, 16);
    centralHeader.writeUInt32LE(data.length, 20);
    centralHeader.writeUInt32LE(data.length, 24);
    centralHeader.writeUInt16LE(fileName.length, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(offset, 42);

    centralParts.push(centralHeader, fileName);

    offset += localHeader.length + fileName.length + data.length;
  }

  const centralDirectory = Buffer.concat(centralParts);
  const localDirectory = Buffer.concat(localParts);

  const endRecord = Buffer.alloc(22);
  endRecord.writeUInt32LE(0x06054b50, 0);
  endRecord.writeUInt16LE(0, 4);
  endRecord.writeUInt16LE(0, 6);
  endRecord.writeUInt16LE(files.length, 8);
  endRecord.writeUInt16LE(files.length, 10);
  endRecord.writeUInt32LE(centralDirectory.length, 12);
  endRecord.writeUInt32LE(localDirectory.length, 16);
  endRecord.writeUInt16LE(0, 20);

  return Buffer.concat([localDirectory, centralDirectory, endRecord]);
}

function fileStub(path: string, purpose: string) {
  if (path.endsWith(".tsx")) {
    return [
      `// Generated by OmegaCrownAI`,
      `// File: ${path}`,
      `// Purpose: ${purpose}`,
      "",
      "export default function GeneratedComponent() {",
      "  return (",
      "    <main>",
      "      <h1>OmegaCrownAI Generated Artifact</h1>",
      "      <p>This file is part of the generated full-stack artifact bundle.</p>",
      "    </main>",
      "  );",
      "}",
      "",
    ].join("\n");
  }

  if (path.endsWith(".ts")) {
    return [
      `// Generated by OmegaCrownAI`,
      `// File: ${path}`,
      `// Purpose: ${purpose}`,
      "",
      "export const generatedArtifactFile = true;",
      "",
    ].join("\n");
  }

  if (path.endsWith(".prisma")) {
    return [
      "// Generated Prisma schema placeholder",
      "datasource db {",
      "  provider = \"postgresql\"",
      "  url      = env(\"DATABASE_URL\")",
      "}",
      "",
      "generator client {",
      "  provider = \"prisma-client-js\"",
      "}",
      "",
      "model ContactSubmission {",
      "  id        String   @id @default(cuid())",
      "  name      String",
      "  email     String",
      "  message   String",
      "  status    String   @default(\"new\")",
      "  createdAt DateTime @default(now())",
      "}",
      "",
      "model OrderInquiry {",
      "  id           String   @id @default(cuid())",
      "  customerName String",
      "  email        String",
      "  itemsJson    Json",
      "  status       String   @default(\"new\")",
      "  createdAt    DateTime @default(now())",
      "}",
      "",
    ].join("\n");
  }

  return `Generated by OmegaCrownAI\nFile: ${path}\nPurpose: ${purpose}\n`;
}

export function createCustomerArtifactPackage(projectId = "project_demo", artifactId?: string) {
  const download = getCustomerDownloadPackageRoute();
  const generated = generateRealFullStackArtifact({
    projectId,
    prompt:
      "Build a full-stack customer-ready website/app with frontend, backend, database, admin, preview, deploy package, validation report, and missing-info report.",
  });

  const artifact = {
    ...generated.artifact,
    artifactId: artifactId || generated.artifact.artifactId,
  };

  const descriptorFiles = [
    ...artifact.frontendFiles,
    ...artifact.backendFiles,
    ...artifact.databaseFiles,
    ...artifact.adminFiles,
    ...artifact.previewFiles,
  ];

  const files: ZipFile[] = [
    {
      path: "README.md",
      content: [
        "# OmegaCrownAI Generated Full-Stack Artifact",
        "",
        `Project ID: ${artifact.projectId}`,
        `Artifact ID: ${artifact.artifactId}`,
        `Customer Ready: ${artifact.customerReady}`,
        `Completeness Score: ${artifact.completenessScore}/100`,
        "",
        "## Included Layers",
        "- Frontend",
        "- Backend/API",
        "- Database/schema",
        "- Admin/review",
        "- Preview sandbox",
        "- Deployment guide",
        "- Validation report",
        "- Missing-info report",
        "",
        "## Run",
        "npm install",
        "npm run build",
        "npm run start",
        "",
      ].join("\n"),
    },
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "omegacrownai-generated-artifact",
          version: "1.0.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "15.0.4",
            react: "latest",
            "react-dom": "latest",
          },
        },
        null,
        2
      ),
    },
    {
      path: ".env.example",
      content: [
        "DATABASE_URL=postgresql://user:password@localhost:5432/generated_app",
        "NEXT_PUBLIC_SITE_URL=https://example.com",
        "OWNER_EMAIL=owner@example.com",
        "ADMIN_AUTH_SECRET=replace-with-secure-secret",
        "",
      ].join("\n"),
    },
    {
      path: "deployment.md",
      content: [
        "# Deployment Guide",
        "",
        "1. Copy the generated package to your host.",
        "2. Configure `.env` from `.env.example`.",
        "3. Run `npm install`.",
        "4. Run `npm run build`.",
        "5. Run `npm run start` or deploy to Vercel/Node/PM2.",
        "",
      ].join("\n"),
    },
    {
      path: "artifact-manifest.json",
      content: JSON.stringify(
        {
          artifactId: artifact.artifactId,
          projectId: artifact.projectId,
          artifactType: artifact.artifactType,
          fileCount: artifact.fileCount,
          customerReady: artifact.customerReady,
          completenessScore: artifact.completenessScore,
          previewPath: artifact.previewPath,
          downloadPath: artifact.downloadPath,
          redacted: true,
        },
        null,
        2
      ),
    },
    {
      path: "validation-report.json",
      content: JSON.stringify(artifact.validation, null, 2),
    },
    {
      path: "missing-info-report.md",
      content: [
        "# Missing Information Report",
        "",
        "The artifact was generated with safe assumptions. Review these items before final launch:",
        "",
        ...artifact.missingBusinessInputs.map((item) => `- ${item}`),
        "",
      ].join("\n"),
    },
    ...descriptorFiles.map((file) => ({
      path: file.path,
      content: fileStub(file.path, file.purpose),
    })),
  ];

  const zip = createZipBuffer(files);
  const filename = `omegacrownai-artifact-${artifact.artifactId}.zip`;

  return {
    ok: true,
    phase: "v24.3 Phase 263",
    service: "Download ZIP Writer Implementation",
    artifact,
    files,
    fileCount: files.length,
    zip,
    zipSizeBytes: zip.length,
    filename,
    contentType: "application/zip",
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
      "X-OmegaCrownAI-Artifact": "customer_full_stack_zip_package",
      "X-OmegaCrownAI-Redacted": "true",
    },
    safety: {
      excludesSecrets: true,
      excludesEnv: true,
      excludesNodeModules: true,
      excludesNextCache: true,
      draftDownloadsAllowed: download.validationBeforeDownload.allowedDraftDownload,
    },
  };
}

export function getDownloadZipWriterImplementation() {
  const sample = createCustomerArtifactPackage("cmoyy1gl700004mkqn7or7hxr");

  return {
    system: "OmegaCrownAI Download ZIP Writer Implementation",
    phase: "v24.3 Phase 263",
    status: "download_zip_writer_implementation_ready",
    purpose:
      "Generate a real in-memory ZIP package for customer full-stack artifacts, including source stubs, README, package.json, .env.example, deployment guide, artifact manifest, validation report, and missing-info report.",
    corePrinciple:
      "Customer exports must be downloadable, useful, redacted, and safe. ZIP packages must include full-stack generated files and reports while excluding secrets and runtime/build folders.",
    route: "/api/projects/[id]/artifacts/[artifactId]/download",
    samplePackage: {
      filename: sample.filename,
      fileCount: sample.fileCount,
      zipSizeBytes: sample.zipSizeBytes,
      contentType: sample.contentType,
      customerReady: sample.artifact.customerReady,
      completenessScore: sample.artifact.completenessScore,
    },
    includedReports: [
      "README.md",
      "package.json",
      ".env.example",
      "deployment.md",
      "artifact-manifest.json",
      "validation-report.json",
      "missing-info-report.md",
    ],
    excludedUnsafeItems: [
      ".env",
      "raw secrets",
      "OAuth tokens",
      "API keys",
      "passwords",
      "private keys",
      "node_modules",
      ".next",
      "server logs",
      "PM2 logs",
    ],
    nextImplementationPhases: [
      "Generated Artifact File System Writer",
      "Artifact History UI Upgrade",
      "Project Distribution Preview Cards",
      "Real Customer Website/App Bundle Export",
    ],
  };
}
