export function getExecutionRunnerPersistentActionLog() {
  return {
    system: "OmegaCrownAI Execution Runner Persistent Action Log",
    phase: "v18.4 Phase 204",
    status: "action_log_blueprint_ready",
    purpose:
      "Define durable execution runner action records so every approved, dry-run, live-run, failed, blocked, or rolled-back action can be replayed, reviewed, audited, and recovered.",
    corePrinciple:
      "No sovereign execution should be untracked. Every execution must have an action id, actor, approval gate, sandbox mode, input/output hashes, result, evidence, error class, and rollback/recovery context.",

    tables: [
      {
        name: "execution_action_runs",
        purpose: "Canonical execution runner action run record.",
        fields: [
          "id",
          "action_id",
          "action_name",
          "execution_category",
          "actor",
          "role",
          "approval_gate",
          "approval_status",
          "sandbox_mode",
          "run_mode",
          "status",
          "risk_level",
          "correlation_id",
          "created_at",
          "started_at",
          "completed_at",
        ],
      },
      {
        name: "execution_action_payloads",
        purpose: "Stores safe input/output hashes and non-secret payload references.",
        fields: [
          "id",
          "execution_action_run_id",
          "input_hash",
          "output_hash",
          "input_ref",
          "output_ref",
          "redaction_status",
          "contains_secret",
        ],
      },
      {
        name: "execution_action_evidence",
        purpose: "Stores build, route, PM2, file, artifact, connector, and validation evidence.",
        fields: [
          "id",
          "execution_action_run_id",
          "evidence_type",
          "evidence_label",
          "evidence_ref",
          "status",
          "created_at",
        ],
      },
      {
        name: "execution_action_errors",
        purpose: "Stores error class, root cause, repair recommendation, and prevention note.",
        fields: [
          "id",
          "execution_action_run_id",
          "error_class",
          "error_message_safe",
          "root_cause",
          "repair_recommendation",
          "prevention_rule",
          "created_at",
        ],
      },
      {
        name: "execution_action_rollbacks",
        purpose: "Stores rollback/recovery availability and action-specific recovery notes.",
        fields: [
          "id",
          "execution_action_run_id",
          "rollback_available",
          "rollback_type",
          "rollback_ref",
          "recovery_note",
          "verified_at",
        ],
      },
    ],

    runModes: [
      "plan_only",
      "dry_run",
      "sandbox_run",
      "approved_live_run",
      "blocked",
      "rolled_back",
    ],

    approvalStatuses: [
      "not_required",
      "pending_approval",
      "approved",
      "denied",
      "expired",
      "blocked_by_policy",
    ],

    actionStatuses: [
      "planned",
      "queued",
      "running",
      "succeeded",
      "failed",
      "blocked",
      "cancelled",
      "rolled_back",
      "needs_review",
    ],

    executionCategories: [
      "software",
      "website_app",
      "trading",
      "automation",
      "api_tool",
      "deployment",
      "connector",
      "memory",
      "governance",
    ],

    errorClasses: [
      "build_error",
      "runtime_error",
      "api_contract_error",
      "artifact_validation_error",
      "security_or_governance_error",
      "deployment_error",
      "connector_error",
      "permission_gate_error",
      "unknown_error",
    ],

    actionRecordShape: {
      actionRunId: "stable action run id",
      actionId: "registered action id",
      actionName: "human-readable action name",
      executionCategory: "software | website_app | trading | automation | api_tool | deployment | connector | memory | governance",
      actor: "user/admin/agent",
      role: "role used to execute or request action",
      approvalGate: "approval gate used",
      approvalStatus: "not_required | pending_approval | approved | denied | blocked_by_policy",
      sandboxMode: "boolean",
      runMode: "plan_only | dry_run | sandbox_run | approved_live_run | blocked | rolled_back",
      status: "planned | queued | running | succeeded | failed | blocked | rolled_back",
      riskLevel: "low | medium | high | blocked_by_default",
      inputHash: "hash of input only, never raw secret",
      outputHash: "hash of output or expected output",
      evidence: ["build result", "route check", "PM2 status", "smoke-test result", "commit hash"],
      errorClass: "optional classified error",
      rollbackAvailable: "boolean",
      recoveryNote: "rollback/recovery note",
      correlationId: "links action to audit, connector, deployment, or memory event",
    },

    replayRules: [
      "Every action run must have action_id and correlation_id.",
      "Every action run must record run_mode and approval_status.",
      "Every live run must include approval evidence unless explicitly low-risk.",
      "Every failed action must include error_class and safe error message.",
      "Every deployment action must include build result, route checks, PM2 status, and rollback reference.",
      "Every connector action must link connector permission gate decision and connector audit record.",
      "Every action payload must store hashes/references only, not raw secrets.",
      "Every high-risk action must include rollback/recovery note before execution.",
    ],

    productionSafetyRules: [
      "No PM2 restart action may run unless build action succeeded.",
      "No deployment action may be marked succeeded without route smoke checks.",
      "No connector external write may run without permission gate allow/approval and audit context.",
      "No financial/live trading/destructive action runs by default.",
      "No action log may store raw secrets.",
      "No customer-ready action status without validation evidence.",
      "No uncontrolled git add . action.",
    ],

    sampleActionRuns: [
      {
        actionId: "deployment.next_build",
        actionName: "Run Next.js production build",
        executionCategory: "deployment",
        approvalStatus: "not_required",
        runMode: "approved_live_run",
        status: "succeeded",
        riskLevel: "medium",
        evidence: ["npm run build output", ".next production build exists"],
        rollbackAvailable: false,
      },
      {
        actionId: "deployment.pm2_restart",
        actionName: "Restart PM2 production process",
        executionCategory: "deployment",
        approvalStatus: "approved",
        runMode: "approved_live_run",
        status: "succeeded",
        riskLevel: "high",
        evidence: ["build passed", "pm2 online", "route smoke checks 200"],
        rollbackAvailable: true,
      },
      {
        actionId: "connector.github.read_issues",
        actionName: "Read GitHub issues",
        executionCategory: "connector",
        approvalStatus: "not_required",
        runMode: "approved_live_run",
        status: "succeeded",
        riskLevel: "low",
        evidence: ["permission gate allow", "connector audit record"],
        rollbackAvailable: false,
      },
      {
        actionId: "connector.stripe.charge_card",
        actionName: "Charge customer card",
        executionCategory: "connector",
        approvalStatus: "blocked_by_policy",
        runMode: "blocked",
        status: "blocked",
        riskLevel: "blocked_by_default",
        evidence: ["permission gate block", "financial action blocked"],
        rollbackAvailable: false,
      },
    ],

    nextImplementationPhases: [
      "Execution Runner Database Migration",
      "Action Log Write API",
      "Action Log Review UI",
      "Deployment Guard Integration",
      "Connector Action Runner Integration",
      "Rollback/Recovery Runner",
    ],
  };
}
