import { getWebsiteBuilderArtifact } from "@/lib/sovereign/website-builder-artifact";

export function getWebsiteStarterFiles() {
  const artifact = getWebsiteBuilderArtifact();

  const files = [
    {
      path: "README.md",
      content: `# Sovereign Website Starter

Generated by OmegaCrownAI Website Builder.

This starter bundle gives you a customer-ready website structure with page copy, SEO metadata, brand direction, conversion planning, and deployment checklist.

## Included Pages

- Home
- About
- Services
- Contact

## Local Use

Open index.html in your browser, or copy these files into your preferred web framework.

## Recommended Build Path

1. Review starter copy.
2. Replace placeholder company details.
3. Add logo and brand assets.
4. Confirm service area and contact details.
5. Review SEO title and description.
6. Test mobile layout.
7. Connect domain and deploy.

## Safety / Quality Notes

This is a starter website artifact. Review all copy before publishing. Confirm legal, pricing, claims, contact details, and service descriptions before going live.
`,
    },
    {
      path: "index.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${artifact.seoMetadata.homeTitle}</title>
  <meta name="description" content="${artifact.seoMetadata.description}" />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact</a>
    </nav>
  </header>

  <main>
    <section class="hero">
      <p class="eyebrow">Customer-ready website</p>
      <h1>${artifact.starterCopy.heroTitle}</h1>
      <p>${artifact.starterCopy.heroSubtitle}</p>
      <div class="actions">
        <a class="button primary" href="./contact.html">Start Website Project</a>
        <a class="button secondary" href="./services.html">View Services</a>
      </div>
    </section>

    <section class="grid">
      ${artifact.homepageSections
        .map(
          (section) => `<article class="card">
        <p class="eyebrow">${section.section}</p>
        <h2>${section.headline}</h2>
        <p>${section.copy}</p>
        <a href="./contact.html">${section.cta} →</a>
      </article>`
        )
        .join("\n      ")}
    </section>

    <section class="cta">
      <h2>Ready to launch a stronger website?</h2>
      <p>Use this starter as your foundation, then customize the copy, brand, services, and deployment path.</p>
      <a class="button primary" href="./contact.html">Contact Us</a>
    </section>
  </main>

  <footer>
    <p>Generated by OmegaCrownAI Website Builder.</p>
  </footer>
</body>
</html>
`,
    },
    {
      path: "about.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>About | Sovereign Website Starter</title>
  <meta name="description" content="Learn about the company, mission, values, and customer-first promise." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">About</p>
      <h1>Built on trust, clarity, and customer service.</h1>
      <p>${artifact.starterCopy.aboutIntro}</p>
    </section>

    <section class="content">
      <h2>Our Mission</h2>
      <p>Help customers choose with confidence by presenting clear information, a professional brand experience, and simple next steps.</p>

      <h2>Why Customers Choose Us</h2>
      <ul>
        <li>Professional communication</li>
        <li>Clear services and expectations</li>
        <li>Customer-first support</li>
        <li>Reliable follow-through</li>
      </ul>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "services.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Services | Sovereign Website Starter</title>
  <meta name="description" content="Explore professional services and choose the right solution for your needs." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">Services</p>
      <h1>Services designed around your customer journey.</h1>
      <p>${artifact.starterCopy.serviceIntro}</p>
    </section>

    <section class="grid">
      <article class="card">
        <h2>Core Service</h2>
        <p>Describe the main service customers need most often.</p>
      </article>
      <article class="card">
        <h2>Premium Service</h2>
        <p>Describe the higher-value or white-glove option.</p>
      </article>
      <article class="card">
        <h2>Custom Service</h2>
        <p>Describe flexible options for unique customer needs.</p>
      </article>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "contact.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Contact | Sovereign Website Starter</title>
  <meta name="description" content="Contact the team to request service, ask a question, or get started." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">Contact</p>
      <h1>Ready to get started?</h1>
      <p>${artifact.starterCopy.contactIntro}</p>
    </section>

    <section class="contact-card">
      <p><strong>Phone:</strong> Add your phone number</p>
      <p><strong>Email:</strong> Add your email address</p>
      <p><strong>Service Area:</strong> Add your service area</p>
      <a class="button primary" href="mailto:hello@example.com">Send Message</a>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "styles.css",
      content: `:root {
  color-scheme: dark;
  --bg: #020617;
  --panel: #0f172a;
  --text: #f8fafc;
  --muted: #94a3b8;
  --cyan: #22d3ee;
  --emerald: #34d399;
  --gold: #facc15;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: radial-gradient(circle at top, rgba(34, 211, 238, 0.18), transparent 40%), var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

a {
  color: inherit;
}

.site-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 24px 6vw;
  border-bottom: 1px solid rgba(255,255,255,0.08);
}

.brand {
  font-weight: 900;
  letter-spacing: 0.04em;
}

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 14px;
  color: var(--muted);
  font-size: 14px;
}

main {
  padding: 48px 6vw;
}

.hero,
.page-hero,
.cta,
.content,
.contact-card {
  max-width: 980px;
  margin: 0 auto 48px;
}

.hero {
  padding: 72px 0;
}

.eyebrow {
  color: var(--cyan);
  font-size: 12px;
  font-weight: 900;
  letter-spacing: 0.22em;
  text-transform: uppercase;
}

h1 {
  font-size: clamp(40px, 8vw, 80px);
  line-height: 0.95;
  margin: 12px 0 20px;
}

h2 {
  margin: 0 0 12px;
}

p {
  color: var(--muted);
  line-height: 1.75;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}

.button {
  display: inline-flex;
  border-radius: 14px;
  padding: 14px 18px;
  font-weight: 900;
  text-decoration: none;
}

.primary {
  background: var(--emerald);
  color: #020617;
}

.secondary {
  border: 1px solid rgba(34, 211, 238, 0.35);
  color: #cffafe;
}

.grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
  margin: 0 auto 48px;
  max-width: 1180px;
}

.card,
.contact-card,
.content,
.cta {
  border: 1px solid rgba(255,255,255,0.08);
  background: rgba(15, 23, 42, 0.72);
  border-radius: 24px;
  padding: 24px;
}

.card a {
  color: var(--cyan);
  font-weight: 900;
  text-decoration: none;
}

footer {
  padding: 32px 6vw;
  border-top: 1px solid rgba(255,255,255,0.08);
  text-align: center;
}

@media (max-width: 900px) {
  .grid {
    grid-template-columns: 1fr;
  }

  .hero {
    padding: 36px 0;
  }
}
`,
    },
    {
      path: "seo.json",
      content: JSON.stringify(artifact.seoMetadata, null, 2),
    },
    {
      path: "brand-direction.json",
      content: JSON.stringify(artifact.brandDirection, null, 2),
    },
    {
      path: "deployment-checklist.md",
      content: `# Deployment Checklist

${artifact.deploymentChecklist.map((item) => `- [ ] ${item}`).join("\n")}

## Conversion Plan

${artifact.conversionPlan.map((item) => `- ${item}`).join("\n")}
`,
    },
  ];

  return {
    department: "website",
    artifactType: "downloadable_website_starter_bundle",
    bundleName: "sovereign-website-starter.zip",
    fileCount: files.length,
    files,
    sourceArtifact: artifact.artifactType,
  };
}
