import { getWebsiteBuilderArtifact } from "@/lib/sovereign/website-builder-artifact";

export function getWebsiteStarterFiles() {
  const artifact = getWebsiteBuilderArtifact();

  const files = [
    {
      path: "README.md",
      content: `# Sovereign Website / App Starter

Generated by OmegaCrownAI Website Builder.

This bundle is designed to be more than a front page. It is a full-stack starter artifact for a customer-ready website or lightweight business app.

## OmegaCrownAI Delivery Standard

Target readiness:

- Minimum customer-ready target: 90%
- Preferred premium target: 100%
- Elite output target: 110%

Every serious customer artifact should include frontend, backend/API where needed, preview/review path, validation, README/run instructions, deployment checklist, and export/download support.

## Included Files

\`\`\`text
README.md
index.html
about.html
services.html
contact.html
admin-review.html
styles.css
data/menu.json
api/contact.js
api/order.js
seo.json
brand-direction.json
deployment-checklist.md
smoke-test-checklist.md
\`\`\`

## What This Starter Includes

- Multi-page frontend
- Contact/order page
- Backend API examples
- Menu/service data file
- Admin/review panel
- SEO metadata
- Brand direction
- Deployment checklist
- Smoke-test checklist

## Local Preview

Open:

\`\`\`text
index.html
\`\`\`

Then inspect:

\`\`\`text
admin-review.html
contact.html
services.html
\`\`\`

## Backend/API Notes

The API files are starter examples. Connect them to your preferred runtime before production:

- Node.js / Express
- Next.js route handlers
- Serverless functions
- Cloudflare Workers
- Vercel Functions

## Customer Review Path

Before launch, review:

1. Page copy
2. Menu/services
3. Contact details
4. Order/contact form fields
5. SEO metadata
6. Mobile layout
7. Deployment checklist
8. Smoke-test checklist

## Production Warning

Do not publish without verifying business details, legal claims, contact details, pricing, service area, privacy requirements, and form handling.
`,
    },
    {
      path: "index.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${artifact.seoMetadata.homeTitle}</title>
  <meta name="description" content="${artifact.seoMetadata.description}" />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website / App Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact / Order</a>
      <a href="./admin-review.html">Review</a>
    </nav>
  </header>

  <main>
    <section class="hero">
      <p class="eyebrow">Full-stack website/app artifact</p>
      <h1>${artifact.starterCopy.heroTitle}</h1>
      <p>${artifact.starterCopy.heroSubtitle}</p>
      <div class="actions">
        <a class="button primary" href="./contact.html">Start Project</a>
        <a class="button secondary" href="./services.html">View Services</a>
      </div>
    </section>

    <section class="proof">
      <div>
        <strong>90–110%</strong>
        <span>Customer-ready target</span>
      </div>
      <div>
        <strong>Frontend + Backend</strong>
        <span>Pages, forms, API starters</span>
      </div>
      <div>
        <strong>Review Ready</strong>
        <span>Admin/review panel included</span>
      </div>
    </section>

    <section class="grid">
      ${artifact.homepageSections
        .map(
          (section) => `<article class="card">
        <p class="eyebrow">${section.section}</p>
        <h2>${section.headline}</h2>
        <p>${section.copy}</p>
        <a href="./contact.html">${section.cta} →</a>
      </article>`
        )
        .join("\n      ")}
    </section>

    <section class="cta">
      <h2>Ready to launch a stronger website?</h2>
      <p>This starter includes frontend pages, backend API examples, review panel, SEO, and deployment checklist.</p>
      <a class="button primary" href="./contact.html">Contact / Order</a>
    </section>
  </main>

  <footer>
    <p>Generated by OmegaCrownAI Website Builder.</p>
  </footer>
</body>
</html>
`,
    },
    {
      path: "about.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>About | Sovereign Website / App Starter</title>
  <meta name="description" content="Learn about the company, mission, values, and customer-first promise." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website / App Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact / Order</a>
      <a href="./admin-review.html">Review</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">About</p>
      <h1>Built on trust, clarity, and customer service.</h1>
      <p>${artifact.starterCopy.aboutIntro}</p>
    </section>

    <section class="content">
      <h2>Our Mission</h2>
      <p>Help customers choose with confidence by presenting clear information, a professional brand experience, and simple next steps.</p>

      <h2>Why Customers Choose Us</h2>
      <ul>
        <li>Professional communication</li>
        <li>Clear services and expectations</li>
        <li>Customer-first support</li>
        <li>Reliable follow-through</li>
      </ul>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "services.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Services / Menu | Sovereign Website / App Starter</title>
  <meta name="description" content="Explore services, menu items, offers, and customer-ready ordering paths." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website / App Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact / Order</a>
      <a href="./admin-review.html">Review</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">Services / Menu</p>
      <h1>Services designed around your customer journey.</h1>
      <p>${artifact.starterCopy.serviceIntro}</p>
    </section>

    <section class="grid three">
      <article class="card">
        <h2>Core Offer</h2>
        <p>Describe the main product, menu item, or service customers need most often.</p>
        <strong>Starting price: Add price</strong>
      </article>
      <article class="card">
        <h2>Premium Offer</h2>
        <p>Describe the higher-value or white-glove option.</p>
        <strong>Starting price: Add price</strong>
      </article>
      <article class="card">
        <h2>Custom Offer</h2>
        <p>Describe flexible options for unique customer needs.</p>
        <strong>Request quote</strong>
      </article>
    </section>

    <section class="cta">
      <h2>Need a custom order or quote?</h2>
      <p>Use the contact/order page to collect customer details and send them to the backend API starter.</p>
      <a class="button primary" href="./contact.html">Start Order</a>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "contact.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Contact / Order | Sovereign Website / App Starter</title>
  <meta name="description" content="Contact the team, request service, place a starter order, or get a quote." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website / App Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./about.html">About</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact / Order</a>
      <a href="./admin-review.html">Review</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">Contact / Order</p>
      <h1>Ready to get started?</h1>
      <p>${artifact.starterCopy.contactIntro}</p>
    </section>

    <section class="form-shell">
      <form id="customer-form">
        <label>
          Name
          <input name="name" required placeholder="Customer name" />
        </label>
        <label>
          Email
          <input name="email" type="email" required placeholder="customer@example.com" />
        </label>
        <label>
          Phone
          <input name="phone" placeholder="Phone number" />
        </label>
        <label>
          Request Type
          <select name="requestType">
            <option>General inquiry</option>
            <option>Order request</option>
            <option>Quote request</option>
            <option>Booking request</option>
          </select>
        </label>
        <label>
          Message
          <textarea name="message" required placeholder="Tell us what you need..."></textarea>
        </label>
        <button class="button primary" type="submit">Submit Request</button>
      </form>

      <aside class="review-note">
        <h2>Backend path</h2>
        <p>This form is wired as a starter. Connect it to api/contact.js or api/order.js in your preferred runtime before production.</p>
      </aside>
    </section>
  </main>

  <script>
    document.getElementById("customer-form").addEventListener("submit", function(event) {
      event.preventDefault();
      alert("Starter form captured. Connect api/contact.js or api/order.js before production.");
    });
  </script>
</body>
</html>
`,
    },
    {
      path: "admin-review.html",
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Admin Review | Sovereign Website / App Starter</title>
  <meta name="description" content="Review readiness, missing details, deployment tasks, and smoke-test checklist." />
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <header class="site-header">
    <div class="brand">Sovereign Website / App Starter</div>
    <nav>
      <a href="./index.html">Home</a>
      <a href="./services.html">Services</a>
      <a href="./contact.html">Contact / Order</a>
    </nav>
  </header>

  <main>
    <section class="page-hero">
      <p class="eyebrow">Review Panel</p>
      <h1>Customer launch readiness review.</h1>
      <p>Use this page to inspect what is ready, what is missing, and what must be checked before launch.</p>
    </section>

    <section class="grid three">
      <article class="card">
        <h2>Frontend</h2>
        <p>Home, about, services/menu, contact/order, and review page included.</p>
      </article>
      <article class="card">
        <h2>Backend</h2>
        <p>Contact/order API starter files included. Connect to runtime before production.</p>
      </article>
      <article class="card">
        <h2>Validation</h2>
        <p>Deployment checklist and smoke-test checklist included.</p>
      </article>
    </section>

    <section class="content">
      <h2>Missing Information Checklist</h2>
      <ul>
        <li>Replace placeholder brand name.</li>
        <li>Add real services/menu items.</li>
        <li>Add real pricing or remove pricing claims.</li>
        <li>Add verified phone, email, service area, and business hours.</li>
        <li>Connect forms to backend runtime.</li>
        <li>Review privacy/legal requirements.</li>
      </ul>
    </section>
  </main>
</body>
</html>
`,
    },
    {
      path: "styles.css",
      content: `:root {
  color-scheme: dark;
  --bg: #020617;
  --panel: #0f172a;
  --text: #f8fafc;
  --muted: #94a3b8;
  --cyan: #22d3ee;
  --emerald: #34d399;
  --gold: #facc15;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: radial-gradient(circle at top, rgba(34, 211, 238, 0.18), transparent 40%), var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

a { color: inherit; }

.site-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 24px 6vw;
  border-bottom: 1px solid rgba(255,255,255,0.08);
}

.brand { font-weight: 900; letter-spacing: 0.04em; }

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 14px;
  color: var(--muted);
  font-size: 14px;
}

main { padding: 48px 6vw; }

.hero, .page-hero, .cta, .content, .form-shell {
  max-width: 1100px;
  margin: 0 auto 48px;
}

.hero { padding: 72px 0; }

.eyebrow {
  color: var(--cyan);
  font-size: 12px;
  font-weight: 900;
  letter-spacing: 0.22em;
  text-transform: uppercase;
}

h1 {
  font-size: clamp(40px, 8vw, 80px);
  line-height: 0.95;
  margin: 12px 0 20px;
}

h2 { margin: 0 0 12px; }

p, li, label {
  color: var(--muted);
  line-height: 1.75;
}

.actions, .proof {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}

.proof div {
  border: 1px solid rgba(255,255,255,0.08);
  background: rgba(15, 23, 42, 0.72);
  border-radius: 18px;
  padding: 16px 18px;
}

.proof strong {
  display: block;
  color: var(--text);
}

.proof span {
  color: var(--muted);
  font-size: 13px;
}

.button {
  display: inline-flex;
  border: 0;
  border-radius: 14px;
  padding: 14px 18px;
  font-weight: 900;
  text-decoration: none;
  cursor: pointer;
}

.primary { background: var(--emerald); color: #020617; }

.secondary {
  border: 1px solid rgba(34, 211, 238, 0.35);
  color: #cffafe;
}

.grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
  margin: 0 auto 48px;
  max-width: 1180px;
}

.grid.three {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.card, .contact-card, .content, .cta, .form-shell, .review-note {
  border: 1px solid rgba(255,255,255,0.08);
  background: rgba(15, 23, 42, 0.72);
  border-radius: 24px;
  padding: 24px;
}

.card a { color: var(--cyan); font-weight: 900; text-decoration: none; }

.form-shell {
  display: grid;
  grid-template-columns: 1.3fr 0.7fr;
  gap: 20px;
}

form {
  display: grid;
  gap: 14px;
}

input, select, textarea {
  width: 100%;
  margin-top: 6px;
  border: 1px solid rgba(255,255,255,0.12);
  background: rgba(2, 6, 23, 0.8);
  color: var(--text);
  border-radius: 12px;
  padding: 12px;
}

textarea { min-height: 130px; }

footer {
  padding: 32px 6vw;
  border-top: 1px solid rgba(255,255,255,0.08);
  text-align: center;
}

@media (max-width: 900px) {
  .grid, .grid.three, .form-shell {
    grid-template-columns: 1fr;
  }

  .hero { padding: 36px 0; }
}
`,
    },
    {
      path: "data/menu.json",
      content: JSON.stringify(
        {
          items: [
            {
              name: "Core Offer",
              description: "Replace with your main menu item, service, or product.",
              price: "Add price",
            },
            {
              name: "Premium Offer",
              description: "Replace with a higher-value option.",
              price: "Add price",
            },
            {
              name: "Custom Offer",
              description: "Use for custom orders, quotes, or bookings.",
              price: "Request quote",
            },
          ],
        },
        null,
        2
      ),
    },
    {
      path: "api/contact.js",
      content: `export async function handleContactRequest(request) {
  const body = await request.json();

  const required = ["name", "email", "message"];
  const missing = required.filter((field) => !body[field]);

  if (missing.length) {
    return {
      ok: false,
      status: 400,
      error: "Missing required fields",
      missing,
    };
  }

  return {
    ok: true,
    status: 200,
    message: "Contact request received.",
    lead: {
      name: body.name,
      email: body.email,
      phone: body.phone || null,
      message: body.message,
      createdAt: new Date().toISOString(),
    },
  };
}
`,
    },
    {
      path: "api/order.js",
      content: `export async function handleOrderRequest(request) {
  const body = await request.json();

  const required = ["name", "email", "requestType", "message"];
  const missing = required.filter((field) => !body[field]);

  if (missing.length) {
    return {
      ok: false,
      status: 400,
      error: "Missing required order fields",
      missing,
    };
  }

  return {
    ok: true,
    status: 200,
    message: "Order or quote request received.",
    order: {
      customerName: body.name,
      email: body.email,
      phone: body.phone || null,
      requestType: body.requestType,
      message: body.message,
      status: "needs_review",
      createdAt: new Date().toISOString(),
    },
  };
}
`,
    },
    {
      path: "seo.json",
      content: JSON.stringify(artifact.seoMetadata, null, 2),
    },
    {
      path: "brand-direction.json",
      content: JSON.stringify(artifact.brandDirection, null, 2),
    },
    {
      path: "deployment-checklist.md",
      content: `# Deployment Checklist

${artifact.deploymentChecklist.map((item) => `- [ ] ${item}`).join("\n")}

## Full-Stack Additions

- [ ] Connect contact form to backend API runtime
- [ ] Connect order/quote flow to backend API runtime
- [ ] Replace placeholder menu/service data
- [ ] Review admin-review.html before launch
- [ ] Confirm privacy/legal requirements for form submissions

## Conversion Plan

${artifact.conversionPlan.map((item) => `- ${item}`).join("\n")}
`,
    },
    {
      path: "smoke-test-checklist.md",
      content: `# Smoke Test Checklist

- [ ] index.html opens
- [ ] about.html opens
- [ ] services.html opens
- [ ] contact.html opens
- [ ] admin-review.html opens
- [ ] styles.css loads
- [ ] seo.json exists
- [ ] brand-direction.json exists
- [ ] data/menu.json exists
- [ ] api/contact.js exists
- [ ] api/order.js exists
- [ ] README explains local preview
- [ ] deployment-checklist.md exists
- [ ] missing information checklist reviewed
`,
    },
  ];

  return {
    department: "website",
    artifactType: "downloadable_full_stack_website_app_bundle",
    bundleName: "sovereign-website-starter.zip",
    fileCount: files.length,
    files,
    sourceArtifact: artifact.artifactType,
    readinessTarget: "90_to_110_percent_customer_ready",
    includesFrontend: true,
    includesBackend: true,
    includesPreview: true,
    includesReviewPanel: true,
    includesSmokeTest: true,
  };
}
