import { prisma } from "@/lib/db";

type PageProps = {
  params: Promise<{ id: string }>;
};

function getTheme(data: any) {
  return data?.theme || data?.colors || {
    background: "#0f0a05",
    surface: "#1b1208",
    primary: "#fff7ed",
    secondary: "#facc15",
    accent: "#f97316",
    muted: "#d6b98c",
  };
}

export default async function PublicGeneratedSite({ params }: PageProps) {
  const { id } = await params;

  const published = await prisma.publishedSite.findUnique({
    where: { slug: id },
  });

  const executionId = published?.executionId || id;

  const execution = await prisma.agentExecution.findUnique({
    where: { id: executionId },
    include: {
      project: true,
    },
  });

  if (!execution) {
    return (
      <main className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Website not found</h1>
          <p className="mt-2 text-white/60">This generated website does not exist.</p>
        </div>
      </main>
    );
  }

  const data: any = execution.execution || {};
  const theme = getTheme(data);

  const hero = data.hero || {
    eyebrow: "AI Generated Website",
    headline: data.title || "Premium Website",
    subheadline: data.tagline || "Generated by OmegaCrownAI.",
    primaryCta: "Get Started",
    secondaryCta: "Learn More",
  };

  const navigation = data.navigation || data.pages || ["Home", "About", "Contact"];
  const products = data.products || [];
  const features = data.features || [];
  const testimonials = data.testimonials || [];
  const assets = data.assets || {};

  return (
    <main
      className="min-h-screen"
      style={{
        background: `linear-gradient(135deg, ${theme.background || "#0f0a05"}, #050505)`,
        color: theme.primary || "#fff7ed",
      }}
    >
      <header className="border-b border-white/10 px-6 py-5 md:px-12">
        <div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-3">
            {assets.logo && (
              <img
                src={assets.logo}
                alt="Logo"
                className="h-12 w-12 rounded-xl bg-white/10 object-contain p-2"
              />
            )}

            <div>
              <div className="text-xl font-bold">
                {data.business || data.title || execution.project.name}
              </div>
              <div className="text-xs opacity-70">
                {data.style || "Premium AI-generated website"}
              </div>
            </div>
          </div>

          <nav className="flex flex-wrap gap-4 text-sm opacity-80">
            {navigation.slice(0, 6).map((item: string) => (
              <span key={item}>{item}</span>
            ))}
          </nav>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[1.1fr_0.9fr] md:px-12 md:py-24">
        <div>
          <div
            className="mb-5 inline-flex rounded-full px-4 py-2 text-xs font-semibold"
            style={{
              background: `${theme.accent || "#f97316"}22`,
              color: theme.secondary || "#facc15",
            }}
          >
            {hero.eyebrow || "Premium Website"}
          </div>

          <h1 className="max-w-4xl text-5xl font-black leading-tight md:text-7xl">
            {hero.headline || data.title || "Beautiful Website Generated by AI"}
          </h1>

          <p className="mt-6 max-w-2xl text-lg leading-8 opacity-75">
            {hero.subheadline ||
              data.tagline ||
              "A polished homepage concept with premium layout, product cards, trust badges, and conversion-focused sections."}
          </p>

          <div className="mt-8 flex flex-wrap gap-4">
            <button
              className="rounded-2xl px-6 py-4 text-sm font-bold text-black shadow-xl"
              style={{ background: theme.secondary || "#facc15" }}
            >
              {hero.primaryCta || "Get Started"}
            </button>

            <button className="rounded-2xl border border-white/15 px-6 py-4 text-sm font-bold">
              {hero.secondaryCta || "Learn More"}
            </button>
          </div>

          <div className="mt-8 flex flex-wrap gap-3">
            {(data.trustBadges || ["AI Generated", "Premium Design", "Project Saved"]).map(
              (badge: string) => (
                <span
                  key={badge}
                  className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs opacity-80"
                >
                  {badge}
                </span>
              )
            )}
          </div>
        </div>

        <div
          className="rounded-[2rem] border border-white/10 p-6 shadow-2xl"
          style={{ background: theme.surface || "#1b1208" }}
        >
          <div className="rounded-[1.5rem] bg-white/10 p-5">
            {assets.hero ? (
              <img
                src={assets.hero}
                alt="Hero"
                className="h-64 w-full rounded-2xl object-cover"
              />
            ) : (
              <div className="h-64 rounded-2xl bg-gradient-to-br from-white/25 to-white/5" />
            )}
          </div>

          <div className="mt-6 grid gap-4">
            {(products.length > 0
              ? products.slice(0, 3)
              : [
                  {
                    name: "Signature Offer",
                    description: "A featured product or service generated from your prompt.",
                    price: "$29",
                  },
                  {
                    name: "Premium Package",
                    description: "A high-value offer designed for conversion.",
                    price: "$59",
                  },
                ]
            ).map((product: any, index: number) => (
              <div
                key={index}
                className="rounded-2xl border border-white/10 bg-black/20 p-5"
              >
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <div className="font-bold">{product.name}</div>
                    <div className="mt-1 text-sm opacity-70">
                      {product.description}
                    </div>
                  </div>
                  <div
                    className="rounded-full px-3 py-1 text-xs font-bold text-black"
                    style={{ background: theme.secondary || "#facc15" }}
                  >
                    {product.price || product.badge || "New"}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-5 px-6 pb-16 md:grid-cols-3 md:px-12">
        {(features.length > 0
          ? features.slice(0, 3)
          : [
              {
                title: "Premium Layout",
                description: "Hero, cards, trust badges, and strong call-to-action sections.",
              },
              {
                title: "Conversion Focused",
                description: "Designed to turn visitors into customers.",
              },
              {
                title: "Mobile Ready",
                description: "Responsive structure for phone and desktop.",
              },
            ]
        ).map((feature: any, index: number) => (
          <div
            key={index}
            className="rounded-3xl border border-white/10 bg-white/5 p-6"
          >
            <div className="text-xl font-bold">{feature.title}</div>
            <div className="mt-3 text-sm leading-7 opacity-70">
              {feature.description}
            </div>
          </div>
        ))}
      </section>

      {testimonials.length > 0 && (
        <section className="mx-auto grid max-w-7xl gap-5 px-6 pb-16 md:grid-cols-2 md:px-12">
          {testimonials.slice(0, 2).map((item: any, index: number) => (
            <div
              key={index}
              className="rounded-3xl border border-white/10 bg-black/20 p-6"
            >
              <div className="text-lg leading-8 opacity-80">“{item.quote}”</div>
              <div className="mt-4 font-bold">{item.name}</div>
            </div>
          ))}
        </section>
      )}

      <footer className="border-t border-white/10 px-6 py-10 md:px-12">
        <div className="mx-auto flex max-w-7xl flex-col gap-5 md:flex-row md:items-center md:justify-between">
          <div>
            <div className="text-3xl font-black">
              {data.footer?.headline || "Ready to get started?"}
            </div>
            <div className="mt-2 text-sm opacity-70">
              {data.tagline || "Built with OmegaCrownAI Website Builder."}
            </div>
          </div>

          <button
            className="rounded-2xl px-6 py-4 text-sm font-bold text-black"
            style={{ background: theme.secondary || "#facc15" }}
          >
            {data.footer?.cta || "Contact Us"}
          </button>
        </div>
      </footer>
    </main>
  );
}
